# Generated by Django 3.1.4 on 2021-01-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_num', models.IntegerField()),
                ('carrier', models.CharField(max_length=20)),
                ('cur_status', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=4)),
                ('ETD', models.CharField(max_length=70)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('scandata', models.JSONField()),
            ],
        ),
    ]
